### ISSUE TITLE
pertpy doesn't work with the recent update of jax 0.7.0

### ISSUE THREAD

**Issue by asalimih** [scverse/pertpy#829]
### Please make sure these conditions are met

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of pertpy.
- [ ] (optional) I have confirmed this bug exists on the main branch.

### Report

Code:

```python
import pertpy as pt
```

Hello,
I installed pertpy and imported it in python but got this error:
```
ImportError: cannot import name 'pjit_p' from 'jax.experimental.pjit'
```
Downgrading jax from 0.7.0 to 0.6.2 solved the problem

### Versions

```markdown

```

**Comment by Zethson** [comment]
Thank you!

This should (also) be reported to numpyro:

```
  File "/home/lukas/miniforge3/envs/pertpy/lib/python3.12/site-packages/numpyro/__init__.py", line 13, in <module>
    from numpyro import compat, diagnostics, distributions, handlers, infer, ops, optim
  File "/home/lukas/miniforge3/envs/pertpy/lib/python3.12/site-packages/numpyro/infer/__init__.py", line 6, in <module>
    from numpyro.infer.elbo import (
  File "/home/lukas/miniforge3/envs/pertpy/lib/python3.12/site-packages/numpyro/infer/elbo.py", line 25, in <module>
    from numpyro.ops.provenance import eval_provenance
  File "/home/lukas/miniforge3/envs/pertpy/lib/python3.12/site-packages/numpyro/ops/provenance.py", line 6, in <module>
    from jax.experimental.pjit import pjit_p
ImportError: cannot import name 'pjit_p' from 'jax.experimental.pjit' (/home/lukas/miniforge3/envs/pertpy/lib/python3.12/site-packages/jax/experimental/pjit.py). Did you mean: 'pjit'?
```

**Comment by Zethson** [comment]
See https://github.com/pyro-ppl/numpyro/issues/2051

**Comment by Zethson** [comment]
Given the numpyro release, this should be addressed now.

Thank you nevertheless for reporting the problem!
